---
name: Clang-format

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: "src"
        exclude: "src/protobuf"
        extensions: "cpp,hpp,h"
        clangFormatVersion: 15
        inplace: True

    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Beats
        author_email: daniel15042014@hotmail.com
        message: "Code format"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
